[build]
    command = "dotnet publish -c Release -o publish"
    publish = "publish"
    functions = "netlify/functions"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/server"
    status = 200 